variables:
  DEPLOY_TARGET: "yourtarget.git"
  MAIN_BRANCH: "main"
  DEVELOP_BRANCH: "develop"
  SSH_KEY: "$SSH_PRIVATE_KEY"
  PROJECT_ACCESS_TOKEN: "$GITLAB_TOKEN"
  KNOWN_HOST: "gitlab.company.com"
  PROJECT_URL: "https://gitlab.company.com/api/v4/projects/#ID/releases"
  WEBHOOK_URL: "$SLACK_WEBHOOK_URL"

image: registry.company.com/cpm/semantic-bash

stages:
  - tag

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan  $KNOWN_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git remote add deploy-target $DEPLOY_TARGET
  - git remote

tag_release_develop:
  stage: tag 
  script:
    - /scripts/parse_commits.sh -b $DEVELOP_BRANCH -t "$GITLAB_TOKEN" -u "$PROJECT_URL" -w "$WEBHOOK_URL"
 
  rules:
    - if: '$CI_COMMIT_BRANCH == $DEVELOP_BRANCH'

tag_release_main:
  stage: tag
  script:
    - /scripts/create_tags.sh -v release -t "$GITLAB_TOKEN" -u "$PROJECT_URL" -w "$WEBHOOK_URL" 
    
  rules:
    - if: '$CI_COMMIT_BRANCH == $MAIN_BRANCH'
