variables:
  DEPLOY_TARGET: "CHANGE ME: yourproject.git"
  MAIN_BRANCH: "CHANGE ME: your production branch"
  DEVELOP_BRANCH: "CHANGE ME: your working branch"
  SSH_KEY: "CHANGE ME: to ssh key"
  PROJECT_ACCESS_TOKEN: "CHANGE ME: to project access token"
  KNOWN_HOST: "CHANGE ME: company repo"

image: CHANGE ME registry.container 

stages:
  - tag

before_script:
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan  $KNOWN_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - git remote add deploy-target $DEPLOY_TARGET
  - git remote

tag_release_develop:
  stage: tag
  script:
    - /scripts/parse_commits.sh -b $DEVELOP_BRANCH -t "$PROJECT_ACCESS_TOKEN"
 
  rules:
    - if: '$CI_COMMIT_BRANCH == $DEVELOP_BRANCH'

tag_release_main:
  stage: tag
  script:
    - /scripts/create_tags.sh -i release -t "$PROJECT_ACCESS_TOKEN"
    
  rules:
    - if: '$CI_COMMIT_BRANCH == $MAIN_BRANCH'
